### ISSUE TITLE
systemd

### ISSUE THREAD

**Issue by talishte** [shelleg/ansible-role-activemq#1]
No systemd compatiblity with centos 7

**Comment by hagzag** [comment]
Sure, I will take a look

**Comment by hagzag** [comment]
Added support for systemd in [v1.0.0](https://github.com/shelleg/ansible-role-activemq/tree/v1.0.0) enjoy.

**Comment by shellegtk** [comment]
Fixed centos/rhel 6 in [v1.0.1](https://github.com/shelleg/ansible-role-activemq/releases/tag/v1.0.1)

**Comment by hagzag** [comment]
Fixed centos/rhel 6 in [v1.0.1](https://github.com/shelleg/ansible-role-activemq/releases/tag/v1.0.1)
